#======================================
# lib
[[plugins]]
name = 'lib/dein'
repo = 'Shougo/dein.vim'

#======================================
# util
[[plugins]]
name = 'util/yankround'
repo = 'LeafCage/yankround.vim'

[[plugins]]
name = 'util/accelerated-jk'
repo = 'rhysd/accelerated-jk'

#======================================
# lang/markdown
[[plugins]]
name  = 'lang/markdown/vim-markdown'
repo  = 'gabrielelana/vim-markdown'
on_ft = ['markdown']

#======================================
# ui
[[plugins]]
name = 'ui/gruvbox'
repo = 'morhetz/gruvbox'
