#======================================
# lib
[[plugins]]
name = 'lib/treesitter'
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
lua << LUA
require ('nvim-treesitter.configs').setup {
  -- ensure_installed = { 'lua', 'toml' },
  highlight = {
    enable = true,
  },
  -- indent = {
  --   enable = true,
  -- },
}
LUA
'''

[[plugins]]
name = 'lib/dap'
repo = 'mfussenegger/nvim-dap'

[[plugins]]
name = 'lib/popup'
repo = 'nvim-lua/popup.nvim'

[[plugins]]
name = 'lib/plenary'
repo = 'nvim-lua/plenary.nvim'

#======================================
# util
[[plugins]]
name = 'util/telescope'
repo = 'nvim-telescope/telescope.nvim'
depends = ['lib/popup', 'lib/prenary']
hook_add = '''
lua << LUA
require ('telescope').setup {
  defaults = {
    mappings = {
      n = { ['<C-k>'] = require ("telescope.actions").close }
    }
  }
}
LUA
nnoremap <leader>g <cmd>Telescope find_files<CR>
nnoremap <leader>b <cmd>Telescope buffers<CR>
'''

#======================================
# ui
[[plugins]]
name = 'ui/tree'
repo = 'kyazdani42/nvim-tree.lua'
hook_add = '''
let g:nvim_tree_width           = 40
"let g:nvim_tree_gitignore       = 1
"let g:nvim_tree_auto_open       = 0
"let g:nvim_tree_follow          = 1
let g:nvim_tree_indent_markers  = 1
let g:nvim_tree_git_hl          = 1
"let g:nvim_tree_tab_open        = 1
let g:nvim_tree_add_trailing    = 1
let g:nvim_tree_group_empty     = 1

nnoremap <leader>f <cmd>NvimTreeToggle<CR>

lua << LUA
local cb = require ("nvim-tree.config").nvim_tree_callback

local list = {
  { key = "<CR>",  cb = cb ("edit")            },
  { key = "o",     cb = cb ("edit")            },
  { key = "i",     cb = cb ("edit")            },
  { key = "l",     cb = cb ("edit")            },
  { key = "e",     cb = cb ("edit")            },
  { key = "E",     cb = cb ("vsplit")          },
  { key = "v",     cb = cb ("vsplit")          },
  { key = "s",     cb = cb ("split")           },
  { key = "<Tab>", cb = cb ("preview")         },
  { key = "R",     cb = cb ("refresh")         },
  { key = "a",     cb = cb ("create")          },
  { key = "d",     cb = cb ("remove")          },
  { key = "r",     cb = cb ("rename")          },
  { key = "x",     cb = cb ("cut")             },
  { key = "c",     cb = cb ("copy")            },
  { key = "p",     cb = cb ("paste")           },
  { key = "[",     cb = cb ("prev_sibling")    },
  { key = "]",     cb = cb ("next_sibling")    },
  { key = ",",     cb = cb ("dir_up")          },
  { key = ".",     cb = cb ("cd")              },
  { key = "q",     cb = cb ("close")           },
  { key = "I",     cb = cb ("toggle_ignored")  },
  { key = "H",     cb = cb ("toggle_dotfiles") },
}

require ("nvim-tree").setup {
  disable_netrw  = false,
  hijack_netrw   = false,

  auto_close = true,

  gitignore = true,

  -- lsp_diagnostics = true,

  view = {
    mappings = {
      list = list
    },
  },

  ignore = {
    ".git",
    ".cache",
    "node_modules",
  }
}


vim.g.nvim_tree_icons = {
  default = " ",
  symlink = " ",
  git = {
    unstaged =  "✗",
    staged =    "✓",
    unmerged =  "",
    renamed =   "➜",
    untracked = "",
    deleted =   "",
    ignored =   "◌"
  },
  folder = {
    default      = "",
    open         = "",
    empty        = "",
    empty_open   = "",
    symlink      = "",
    symlink_open = "",
  },
}
LUA
'''
