#======================================
# lib
[[plugins]]
name = 'lib/dein'
repo = 'Shougo/dein.vim'

[[plugins]]
name   = 'lib/coc'
repo   = 'neoclide/coc.nvim'
rev    = 'release'
merged = '0'

#======================================
# util
[[plugins]]
name = 'util/yankround'
repo = 'LeafCage/yankround.vim'

[[plugins]]
name = 'util/accelerated-jk'
repo = 'rhysd/accelerated-jk'

[[plugins]]
name = 'util/commentary'
repo = 'tpope/vim-commentary'

[[plugins]]
name = 'util/fugitive'
repo = 'tpope/vim-fugitive'

[[plugins]]
name = 'util/gitgutter'
repo = 'airblade/vim-gitgutter'

[[plugins]]
name = 'util/surround'
repo = 'tpope/vim-surround'

[[plugins]]
name = 'util/deol'
repo = 'Shougo/deol.nvim'

[[plugins]]
name = 'util/auto-pairs'
repo = 'jiangmiao/auto-pairs'

#======================================
# ui
[[plugins]]
name = 'ui/gruvbox'
repo = 'morhetz/gruvbox'

[[plugins]]
name = 'ui/minimalist'
repo = 'dikiaap/minimalist'

[[plugins]]
name = 'ui/onedark'
repo = 'joshdick/onedark.vim'

[[plugins]]
name = 'ui/better-whitespace'
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
name    = 'ui/airline'
repo    = 'vim-airline/vim-airline'
depends = ['ui/vim-airline-themes']

[[plugins]]
name = 'ui/airline-themes'
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
name = 'ui/defx'
repo = 'Shougo/defx.nvim'

[[plugins]]
name = 'ui/defx-icons'
repo = 'kristijanhusak/defx-icons'

[[plugins]]
name = 'ui/defx-git'
repo = 'kristijanhusak/defx-git'

[[plugins]]
name = 'ui/indentline'
repo = 'Yggdroot/indentLine'

[[plugins]]
name = 'ui/goyo'
repo = 'junegunn/goyo.vim'

[[plugins]]
name = 'ui/devicons'
repo = 'ryanoasis/vim-devicons'

[[plugins]]
name = 'ui/vista'
repo = 'liuchengxu/vista.vim'

#======================================
# lang/c++
[[plugins]]
name  = 'lang/c++/lsp-cxx-highlight'
repo  = 'jackguo380/vim-lsp-cxx-highlight'
on_ft = ['cpp', 'c']

[[plugins]]
name  = 'lang/c++/clang-format'
repo  = 'rhysd/vim-clang-format'
on_ft = ['cpp', 'c']

#======================================
# lang/haskell
[[plugins]]
name  = 'lang/haskell/haskell'
repo  = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

#======================================
# lang/html
[[plugins]]
name  = 'lang/html/emmet'
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'phtml', 'xml']

[[plugins]]
name  = 'lang/html/closetag'
repo  = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'phtml', 'xml']

#======================================
# lang/typescript
[[plugins]]
name  = 'lang/typescript/typescript'
repo  = 'leafgarland/typescript-vim'
on_ft = ['ts', 'tsx']

# lang/typescript
[[plugins]]
name  = 'lang/typescript/jsx-typescript'
repo  = 'peitalin/vim-jsx-typescript'
on_ft = ['jsx', 'tsx']

#======================================
# lang/toml
[[plugins]]
name  = 'lang/toml/toml'
repo  = 'cespare/vim-toml'
on_ft = ['toml']

#======================================
# lang/vala
[[plugins]]
name  = 'lang/vala/vala'
repo  = 'arrufat/vala.vim'
on_ft = ['vala']

#======================================
# lang/swift
[[plugins]]
name  = 'lang/swift/swift'
repo  = 'keith/swift.vim'
on_ft = ['swift']

#======================================
# lang/go
[[plugins]]
name = 'lang/go/go'
repo = 'fatih/vim-go'
on_ft = ['go']

#======================================
# lang/latex
[[plugins]]
name = 'lang/latex/tex'
repo = 'lervag/vimtex'
on_ft = ['tex']
