#======================================
# lib
[[plugins]]
name = 'lib/dein'
repo = 'Shougo/dein.vim'

[[plugins]]
name   = 'lib/coc'
repo   = 'neoclide/coc.nvim'
rev    = 'release'
merged = 0

#======================================
# util
[[plugins]]
name = 'util/yankround'
repo = 'LeafCage/yankround.vim'

[[plugins]]
name = 'util/accelerated-jk'
repo = 'rhysd/accelerated-jk'

[[plugins]]
name = 'util/repeat'
repo = 'tpope/vim-repeat'

[[plugins]]
name = 'util/gitgutter'
repo = 'airblade/vim-gitgutter'

[[plugins]]
name = 'util/surround'
repo = 'tpope/vim-surround'

[[plugins]]
name = 'util/auto-pairs'
repo = 'jiangmiao/auto-pairs'

[[plugins]]
name = 'util/visual-multi'
repo = 'mg979/vim-visual-multi'

[[plugins]]
name = 'util/sonictemplate'
repo = 'mattn/vim-sonictemplate'

[[plugins]]
name = 'util/tcomment'
repo = 'tomtom/tcomment_vim'

#======================================
# ui
[[plugins]]
name = 'ui/onedark'
repo = 'joshdick/onedark.vim'

[[plugins]]
name = 'ui/better-whitespace'
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
name    = 'ui/airline'
repo    = 'vim-airline/vim-airline'
depends = ['ui/vim-airline-themes']

[[plugins]]
name = 'ui/airline-themes'
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
name = 'ui/indent-guides'
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_exclude_filetypes = [
        \ 'help',
        \ 'coc-explorer',
        \ 'haskell',
        \ 'purescript',
        \ 'vista'
        \ ]
  let g:indent_guides_guide_size  = 1
  let g:indent_guides_auto_colors = 0
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=239 ctermfg=236
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=232 ctermfg=236
  let g:indent_guides_enable_on_vim_startup = 1
'''

[[plugins]]
name = 'ui/devicons'
repo = 'ryanoasis/vim-devicons'

[[plugins]]
name = 'ui/vista'
repo = 'liuchengxu/vista.vim'

[[plugins]]
name = 'ui/rainbow-parentheses'
repo = 'junegunn/rainbow_parentheses.vim'
hook_add = '''
  autocmd FileType * RainbowParentheses
'''
