#======================================
# lib
[[plugins]]
name = 'lib/dein'
repo = 'Shougo/dein.vim'

[[plugins]]
name   = 'lib/coc'
repo   = 'neoclide/coc.nvim'
rev    = 'release'
merged = '0'

#======================================
# util
[[plugins]]
name = 'util/yankround'
repo = 'LeafCage/yankround.vim'

[[plugins]]
name = 'util/accelerated-jk'
repo = 'rhysd/accelerated-jk'

[[plugins]]
name = 'util/vim-commentary'
repo = 'tpope/vim-commentary'

[[plugins]]
name = 'util/vim-fugitive'
repo = 'tpope/vim-fugitive'

[[plugins]]
name = 'util/vim-gitgutter'
repo = 'airblade/vim-gitgutter'

[[plugins]]
name = 'util/surround'
repo = 'tpope/vim-surround'

#======================================
# ui
[[plugins]]
name = 'ui/gruvbox'
repo = 'morhetz/gruvbox'

[[plugins]]
name = 'ui/vim-trailing-whitespace'
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
name    = 'ui/vim-airline'
repo    = 'vim-airline/vim-airline'
depends = ['ui/vim-airline-themes']

[[plugins]]
name = 'ui/vim-airline-themes'
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
name = 'ui/tagbar'
repo = 'majutsushi/tagbar'

[[plugins]]
name = 'ui/indentLine'
repo = 'Yggdroot/indentLine'

[[plugins]]
name = 'ui/nerdtree'
repo = 'scrooloose/nerdtree'

[[plugins]]
name    = 'ui/vim-nerdtree-tabs'
repo    = 'jistr/vim-nerdtree-tabs'
depends = ['ui/nerdtree']

[[plugins]]
name    = 'ui/nerdtree-git-plugin'
repo    = 'Xuyuanp/nerdtree-git-plugin'
depends = ['ui/nerdtree']

[[plugins]]
name  = 'ui/goyo'
repo  = 'junegunn/goyo.vim'

[[plugins]]
name = 'ui/vim-devicons'
repo = 'ryanoasis/vim-devicons'

#======================================
# lang/html
[[plugins]]
name  = 'lang/html/emmet-vim'
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'phtml', 'xml']

[[plugins]]
name  = 'lang/html/vim-closetag'
repo  = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'phtml', 'xml']

#======================================
# lang/typescript
[[plugins]]
name  = 'lang/typescript/typescript-vim'
repo  = 'leafgarland/typescript-vim'
on_ft = ['ts', 'tsx']

# lang/typescript
[[plugins]]
name  = 'lang/typescript/vim-jsx-typescript'
repo  = 'peitalin/vim-jsx-typescript'
on_ft = ['jsx', 'tsx']

#======================================
# lang/toml
[[plugins]]
name  = 'lang/toml/vim-toml'
repo  = 'cespare/vim-toml'
on_ft = ['toml']

#======================================
# lang/vala
[[plugins]]
name  = 'lang/vala/vala'
repo  = 'arrufat/vala.vim'
on_ft = ['vala']

#======================================
# lang/swift
[[plugins]]
name  = 'lang/swift/swiftc'
repo  = 'keith/swift.vim'
on_ft = ['swift']

#======================================
# lang/go
[[plugins]]
name = 'lang/go/vim-go'
repo = 'fatih/vim-go'
on_ft = ['go']

#======================================
# lang/latex
[[plugins]]
name = 'lang/latex/vimtex'
repo = 'lervag/vimtex'
on_ft = ['tex']
