#======================================
# lib
[[plugins]]
name = 'lib/dein'
repo = 'Shougo/dein.vim'

[[plugins]]
name   = 'lib/coc'
repo   = 'neoclide/coc.nvim'
rev    = 'release'
merged = 0

#======================================
# util
[[plugins]]
name = 'util/yankround'
repo = 'LeafCage/yankround.vim'

[[plugins]]
name = 'util/accelerated-jk'
repo = 'rhysd/accelerated-jk'

[[plugins]]
name = 'util/commentary'
repo = 'tpope/vim-commentary'

[[plugins]]
name = 'util/fugitive'
repo = 'tpope/vim-fugitive'

[[plugins]]
name = 'util/gitgutter'
repo = 'airblade/vim-gitgutter'

[[plugins]]
name = 'util/surround'
repo = 'tpope/vim-surround'

[[plugins]]
name = 'util/auto-pairs'
repo = 'jiangmiao/auto-pairs'

[[plugins]]
name = 'visual-multi'
repo = 'mg979/vim-visual-multi'

#======================================
# ui
[[plugins]]
name = 'ui/onedark'
repo = 'joshdick/onedark.vim'

[[plugins]]
name = 'ui/better-whitespace'
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
name    = 'ui/airline'
repo    = 'vim-airline/vim-airline'
depends = ['ui/vim-airline-themes']

[[plugins]]
name = 'ui/airline-themes'
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
name = 'ui/indentline'
repo = 'Yggdroot/indentLine'

[[plugins]]
name = 'ui/devicons'
repo = 'ryanoasis/vim-devicons'

[[plugins]]
name = 'ui/vista'
repo = 'liuchengxu/vista.vim'

