#======================================
# lang/c++
[[plugins]]
name  = 'lang/c++/lsp-cxx-highlight'
repo  = 'jackguo380/vim-lsp-cxx-highlight'
on_ft = ['cpp', 'c']

[[plugins]]
name  = 'lang/c++/clang-format'
repo  = 'rhysd/vim-clang-format'
on_ft = ['cpp', 'c']

#======================================
# lang/haskell
[[plugins]]
name  = 'lang/haskell/haskell'
repo  = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]]
name  = 'lang/haskell/stylish-haskell'
repo  = 'nbouscal/vim-stylish-haskell'
on_ft = ['haskell']

#======================================
# lang/html
[[plugins]]
name  = 'lang/html/emmet'
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'xhtml', 'phtml', 'xml']

[[plugins]]
name  = 'lang/html/closetag'
repo  = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'phtml', 'xml']

#======================================
# lang/pug
[[plugins]]
name  = 'lang/pug/pug'
repo  = 'digitaltoad/vim-pug'
on_ft = ['pug']

#======================================
# lang/typescript
[[plugins]]
name  = 'lang/typescript/typescript'
repo  = 'leafgarland/typescript-vim'
on_ft = ['ts', 'tsx']

# lang/typescript
[[plugins]]
name  = 'lang/typescript/jsx-typescript'
repo  = 'peitalin/vim-jsx-typescript'
on_ft = ['jsx', 'tsx']

#======================================
# lang/toml
[[plugins]]
name  = 'lang/toml/toml'
repo  = 'cespare/vim-toml'
on_ft = ['toml']

#======================================
# lang/swift
[[plugins]]
name  = 'lang/swift/swift'
repo  = 'keith/swift.vim'
on_ft = ['swift']

#======================================
# lang/go
[[plugins]]
name = 'lang/go/go'
repo = 'fatih/vim-go'
on_ft = ['go']

#======================================
# lang/latex
[[plugins]]
name = 'lang/latex/tex'
repo = 'lervag/vimtex'
on_ft = ['tex']

