#======================================
# lang/c++
[[plugins]]
name  = 'lang/c++/lsp-cxx-highlight'
repo  = 'jackguo380/vim-lsp-cxx-highlight'
on_ft = ['cpp', 'c']

#======================================
# lang/haskell
[[plugins]]
name  = 'lang/haskell/haskell'
repo  = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']
hook_source = '''
let g:haskell_enable_quantification   = 1
let g:haskell_enable_recursivedo      = 1
let g:haskell_enable_arrowsyntax      = 1
let g:haskell_enable_pattern_synonyms = 1
let g:haskell_enable_typeroles        = 1
let g:haskell_enable_static_pointers  = 1
let g:haskell_backpack                = 1

let g:haskell_indent_disable          = 0
let g:haskell_indent_if               = 3
let g:haskell_indent_case             = 2
let g:haskell_indent_case_alternative = 2
let g:haskell_indent_let              = 4
let g:haskell_indent_in               = 1
let g:haskell_indent_where            = 6
let g:haskell_indent_before_where     = 2
let g:haskell_indent_after_bare_where = 2
let g:haskell_indent_do               = 3
let g:haskell_indent_guard            = 2
'''

#======================================
# lang/purescript
[[plugins]]
name  = 'lang/purescript/purescript'
repo  = 'purescript-contrib/purescript-vim'
on_ft = ['purescript']
hook_source = '''
let g:purescript_indent_disable          = 0
let g:purescript_indent_if               = 3
let g:purescript_indent_case             = 2
let g:purescript_indent_case_alternative = 2
let g:purescript_indent_let              = 4
let g:purescript_indent_in               = 1
let g:purescript_indent_where            = 6
let g:purescript_indent_before_where     = 2
let g:purescript_indent_after_bare_where = 2
let g:purescript_indent_do               = 3
'''

#======================================
# lang/toml
[[plugins]]
name  = 'lang/toml/toml'
repo  = 'cespare/vim-toml'
on_ft = ['toml']

#======================================
# lang/swift
[[plugins]]
name  = 'lang/swift/swift'
repo  = 'keith/swift.vim'
on_ft = ['swift']

#======================================
# lang/go
[[plugins]]
name  = 'lang/go/goimports'
repo  = 'mattn/vim-goimports'
on_ft = ['go']

#======================================
# lang/latex
[[plugins]]
name  = 'lang/latex/tex'
repo  = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
let g:Tex_Folding     = 0
let g:Tex_AutoFolding = 0
let g:tex_conceal     = 0
let g:tex_flavor      = "latex"

let g:vimtex_syntax_conceal_default = 0

let g:vimtex_syntax_packages =
      \ {
      \   'luacode'  : { 'load' : 2 },
      \   'listings' : { 'load' : 2 },
      \ }
'''
