#!/usr/bin/env perl
#$latex            = 'uplatex -shell-escape -halt-on-error';
#$latex_silent     = 'uplatex -shell-escape -halt-on-error -interaction=nonstopmode';
#$bibtex           = 'pbibtex';
#$dvipdf           = 'dvipdfmx %O -o %D %S';
#$makeindex        = 'mendex %O -o %D %S';
#$max_repeat       = 5;
#$pdf_mode         = 3; # generates pdf via dvipdfmx

$pdf_mode = 1;
$pdflatex = 'lualatex -shell-escape -file-line-error -halt-on-error -interaction=nonstopmode %O %S';
$bibtex   = 'pbibtex %O %B';

$aux_dir  = "./build";
$out_dir  = "./build";

# Prevent latexmk from removing PDF after typeset.
# This enables Skim to chase the update in PDF automatically.
$pvc_view_file_via_temporary = 0;

# ...
$pdf_previewer = "echo %S";
